### ISSUE TITLE
site launch checklist

### ISSUE THREAD

**Issue by derekeder** [derekeder/oak-park-budget#6]
From the [DataMade Site Launch Checklist](https://github.com/datamade/site-launch-checklist)

## Deployment and DNS

* [x] Create a production deployment
* [x] Double check that production-level resources have been provisioned
* [x] Purchase your domain and create the DNS record to point it at your production deployment
* [x] Set up SSL

## Web Search Indexing

* [x] Allow indexing of your production site
* [x] Redirect the www subdomain to your root domain
* [x] [Set a canonical URL](https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls) to prevent duplicate search results

## Google Analytics

* [x] Create a [Google Analytics](http://www.google.com/analytics/) account
* [x] Add [the Google Analytics script](https://developers.google.com/analytics/devguides/collection/analyticsjs) to your site
* [x] Set up [Google Webmaster Tools](https://www.google.com/webmasters/tools/home?hl=en) and [verify site](https://support.google.com/webmasters/answer/9008080?hl=en)
* [x] Link Webmaster Tools to Google Analytics
* [ ] Optional: Set up relevant Goals and Funnels in Google Analytics

## Sharing & Rich Snippets

* [x] Create a share card using [Canva](http://canva.com/) or a similar tool
* [x] Set up general meta tags
    ```html
    <meta name="description" content="${SITE_NAME}" />
    <meta name="author" content="${SITE_AUTHOR}" />
    ```
* [x] Set up Facebook meta tags & validate [here](https://developers.facebook.com/tools/debug/)
    ```html
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="${SITE_NAME}">
    <meta property="og:description" content="${SITE_DESCRIPTION}">
    <meta property="og:image" content="${SHARE_CARD_URL}">
    <meta property="og:title" content="${PAGE_TITLE}">
    <meta property="og:url" content="${PAGE_URL}">
    ```
* [x] Set up Twitter meta tags & validate [here](https://cards-dev.twitter.com/validator)
    ```html
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="${SITE_NAME}">
    <meta name="twitter:creator" content="${SITE_AUTHOR}">
    <meta name="twitter:description" content="${SITE_DESCRIPTION}">
    <meta name="twitter:image" content="${SHARE_CARD_URL}">
    <meta name="twitter:title" content="${PAGE_TITLE}">
    <meta name="twitter:url" content="${PAGE_URL}">
    ```

## Miscellaneous Polish

* [x] Add favicons and Apple touch icons (http://www.favicomatic.com/)
* [ ] Add custom 404 & 500 error pages

## Browser and mobile compatibility

* [ ] Use BrowserStack to confirm that your site is compatible with the browsers you wish to support

Using BrowserStack's mobile device emulators and/or your own mobile device, confirm that:

* [x] Scrolling is easy
* [x] Nav bar works
* [x] Hoverable things are tappable
* [ ] Charts and maps look ok

## Printer Friendliness

Dynamic sizing, dark backgrounds, and interactivity don't play well with printers.

Pick one:

* [ ] Make a print stylesheet using a `@media print {}` media query, then add it to your site with `<link rel="stylesheet" type="text/css" href="css/print.css" media="print">`

- or -

* [ ] Use your browser's dev tools to remove offending elements (like sticky footers), alter colors where needed, and [screenshot the entire page](https://stackoverflow.com/a/14830242).
* [ ] Add a link to the printer-friendly version to your website.

## GitHub README

If the site is open source, make sure the README.md is complete and accurate.

Here's a few good examples:

- [LA Metro Councilmatic](https://github.com/datamade/la-metro-councilmatic)
- [Illinois Sunshine](https://github.com/datamade/illinois-sunshine/blob/master/README.md)

The README should generally contain information on the following:

* [ ] Project overview
* [ ] System-level dependencies
* [ ] Running locally
* [ ] Bug reports and contributing
* [ ] Copyright and license

**Comment by derekeder** [comment]
good to go for now!
