### ISSUE TITLE
site launch sequencing

### ISSUE THREAD

**Issue by derekeder** [derekeder/oak-park-budget#7]
* [x] Alicia to get Derek the 2017 budget
* [x] Derek merges the spreadsheets in #2 
* [ ] Alicia to add function codes
* [x] Send function codes over to David for review
* [x] Finish About #3 and FAQ #4 pages
* [x] Derek to wrap up site launch checklist #6

**Comment by derekeder** [comment]
we're launching without the function codes for now
